version: "1"
rules:
  - base: master
    upstream: MeteorDevelopment:master
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: main
    upstream: MeteorDevelopment:master
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1