name: DeepSource

on:
    push:
        branches:
            - master

jobs:
    DeepSource:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                ref: ${{ github.event.pull_request.head.sha }}
            - name: Report results to DeepSource
              run: |
                  # Tests have finished and a test coverage report is available

                  # Install deepsource CLI
                    curl https://deepsource.io/cli | sh

                  # From the root directory, run the report coverage command
                    ./bin/deepsource report --analyzer test-coverage --key python --value-file ./src/main/java

              env:
                DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
